services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: foka_vote
      POSTGRES_USER: foka
      POSTGRES_PASSWORD: foka
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: sh -c "npx prisma generate --schema=apps/api/prisma/schema.prisma && npm run dev:api"
    environment:
      NODE_ENV: development
      PORT: 3000
      HOST: 0.0.0.0
      DATABASE_URL: postgresql://foka:foka@db:5432/foka_vote?schema=public
      ADMIN_PASSWORD_HASH: '7243d45a465fcdccf76b5bd4b4cda97e:a0b416070f6e82cb782a872231c39c710aae14c74b5243e32b9c38e7fe6328a7c9cde4aafa59fb84a18f77410000a2a88e37c36ad28b371b0643f91cc7fe5b37'
      COOKIE_SECRET: 1849ff17de31b93f209ff9fa639e5df12fd367cda3e7778e346ebf2bea7319f2
    volumes:
      - .:/app
      - api_node_modules:/app/node_modules
      - api_prisma_client:/app/apps/api/node_modules/.prisma
    ports:
      - '3000:3000'
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: npm run dev:web
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:3000
      CHOKIDAR_USEPOLLING: 'true'
    volumes:
      - .:/app
      - web_node_modules:/app/node_modules
    ports:
      - '5173:5173'
    depends_on:
      - api

volumes:
  db_data:
  api_node_modules:
  api_prisma_client:
  web_node_modules:
