export const NICKNAME_POOL: readonly string[] = [
  'Zebra Prześwietleń',
  'Kameleon Balansu Bieli',
  'Panda Czerni I Bieli',
  'Mątwa Sepii',
  'Biedronka Czerwonego Kanału',
  'Tukan Nasycenia Barw',
  'Krewetka Szesnastu Bitów',
  'Sowa Wysokiego ISO',
  'Nietoperz Nocnego Autofokusa',
  'Sokół Śledzenia Ostrości',
  'Koliber Ośmiu Tysięcznych',
  'Zając Trybu Seryjnego',
  'Ślimak Długiej Ekspozycji',
  'Świetlik Malowania Światłem',
  'Foka Złotej Godziny',
  'Modliszka Statywu',
  'Pies Poruszonego Kadru',
  'Kot Który Wszedł W Kadr',
  'Gołąb W Tle',
  'Kret Braku Ostrości',
  'Jeż Wyostrzania',
  'Owca Rozmycia Gaussa',
  'Bóbr Kadrowania',
  'Pająk Linii Pomocniczych',
  'Ośmiornica Ośmiu Warstw',
  'Papuga Stempla Klonującego',
  'Kukułka Kopiuj Wklej',
  'Sroka Jasnych Refleksów',
  'Jamnik Formatu Panoramicznego',
  'Żyrafa Kadru Pionowego',
  'Krab Panoramowania',
  'Lemur Otwartej Przysłony',
  'Mrówkojad Długiego Obiektywu',
  'Niedźwiedź Szerokiego Kąta',
  'Ryba Rybiego Oka',
  'Pawie Oko Obiektywu',
  'Motyl Odbicia Lustrzanego',
  'Pchła Makrofotografii',
  'Roztocze Jednego Piksela',
  'Wieloryb RAW',
  'Mrówka Maszerującego Zaznaczenia',
  'Chomik Schowka',
  'Wiewiórka Kopii Zapasowej',
  'Słoń Historii Zmian',
  'Złota Rybka Niezapisanego Pliku',
  'Wąż Krzywej Beziera',
  'Gąsienica Punktów Kontrolnych',
  'Rak Lasso',
  'Ćma Trybu Ciemnego',
  'Stonoga Skrótów Klawiszowych',
  'Gekon Czułości Nacisku',
  'Pszczoła Siatki Sześciokątnej',
  'Flaming Na Sztaludze',
  'Wielbłąd Włosia Pędzla',
  'Borsuk Miękkiego Pędzla',
  'Dzik Twardej Szczeciny',
  'Gęś Gęsiego Pióra',
  'Kałamarnica Kałamarza',
  'Czerwiec Karminu',
  'Jedwabnik Sitodruku',
  'Kornik Drzeworytu',
  'Krab Cyrkla',
] as const;
